### ISSUE TITLE
How can we use the dataset to train a classifier and the dataset itself was labeled using a heuristics and rules?

### ISSUE THREAD

**Issue by MahmoudWahdan** [bakrianoo/Datasets#1]
From the README, you said: "A corpus of Arabic tweets categorized to positive and negative sentiments based on some emoji characters appearance". 
How can we use the dataset to train a classifier and the dataset itself was labeled using a heuristics and rules?

**Comment by bakrianoo** [comment]
I do not recommend to build a classifier using this corpus before filterring and relabelling the tweets. You must not build a classifier using an automated labeled train data. It does not make sense.

The power of this repo is in the data and its size. There are many tasks you could utilize these tweets in. Building word embeddings, language models, keyword extraction, emoji analysis, dialects detection, network graph analysis, etc..

**Comment by MahmoudWahdan** [comment]
So, I think the dataset shouldn't be divided into 2 separate files. It's misleading.
It will be also very beneficial if you share the approach to extract the dataset. I mean is it specific queries for some brands or events or hashtags? Is it for a specific region? What the period of time? ...etc

**Comment by bakrianoo** [comment]
Just merge the files if you do not need this seperation. Please, it is not a research paper or even a complete project. This data for just helping who need it. So I do not have to provide more than the download link.

Twitter scrapping is not a rocket science, you can search for it and you will find tens of tutorials.

This board is just for "issues" not for general talking. Mail me if you need more details on bakrianoo at gmail.
Thanks
